port:  5000
markdown: kramdown
name: Chi Hack Night
url: http://chihacknight.org
title: Chi Hack Night
description: "Chicago's weekly event to build, share, and learn about civic tech."
encoding: utf-8
timezone: America/Chicago
navigation:
- text: Events
  url: /events/index.html
  category: events
- text: Breakout groups
  url: /breakouts.html
- text: About
  url: /about.html
- text: Contact us
  url: /contact-us.html